tap "heroku/brew"
tap "jesseduffield/lazygit"

brew "mas"

# Mac Apps

cask "chrome"
cask "cursor"
cask "iterm2"
cask "ngrok"
cask "visual-studio-code"
cask "vnc-viewer"

mas "Affinity Designer 2", id: 1616831348
mas "Amphetamine", id: 937984704
mas "Color Picker", id: 1545870783
mas "CrystalFetch", id: 6454431289
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Motion", id: 434290957
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
mas "UTM", id: 1538878817
mas "Windows App", id: 1295203466

# Terminal utilities

brew "ack"
brew "ast-grep"
brew "bat"
brew "eza"
brew "fastfetch"
brew "fd"
brew "font-meslo-lg-nerd-font"
brew "fzf"
brew "oh-my-posh"
brew "ripgrep"
brew "stow"
brew "tree"
brew "zoxide"

# Development tools

brew "git"
brew "gnupg"
brew "heroku"
brew "lazydocker"
brew "lazygit"
brew "libssl@3"
brew "libyaml"
brew "neovim"

# Programming Languages

brew "golang"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "python@3.13"
brew "rust"

# Development libraries
brew "libpq", link: true

# VSCode extensions

vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "clemenspeters.format-json"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "denoland.vscode-deno"
vscode "dsznajder.es7-react-js-snippets"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.makefile-tools"
vscode "shopify.ruby-lsp"
vscode "vscodevim.vim"

