#!/bin/zsh

cursor --install-extension anthropic.claude-code
cursor --install-extension anysphere.cursorpyright
cursor --install-extension bierner.markdown-mermaid
cursor --install-extension bradlc.vscode-tailwindcss
cursor --install-extension clemenspeters.format-json
cursor --install-extension dart-code.dart-code
cursor --install-extension dart-code.flutter
cursor --install-extension denoland.vscode-deno
cursor --install-extension dsznajder.es7-react-js-snippets
cursor --install-extension docker.docker
cursor --install-extension eamodio.gitlens
cursor --install-extension enkia.tokyo-night
cursor --install-extension esbenp.prettier-vscode
cursor --install-extension golang.go
cursor --install-extension laurencebahiirwa.deno-std-lib-snippets
cursor --install-extension mechatroner.rainbow-csv
cursor --install-extension monokai.theme-monokai-pro-vscode
cursor --install-extension ms-azuretools.vscode-containers
cursor --install-extension ms-azuretools.vscode-docker
cursor --install-extension ms-python.debugpy
cursor --install-extension ms-python.python
cursor --install-extension ms-python.vscode-pylance
cursor --install-extension ms-python.vscode-python-envs
cursor --install-extension ms-vscode-remote.remote-containers
cursor --install-extension ms-vscode.makefile-tools
cursor --install-extension shopify.ruby-lsp
cursor --install-extension tamasfe.even-better-toml
cursor --install-extension vscodevim.vim
