tap "heroku/brew"
tap "jesseduffield/lazygit"
tap "cwsaylor/tap"

cask "claude"
cask "cursor"
cask "github"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "ngrok"
cask "visual-studio-code"

# Terminal utilities

brew "ast-grep"
brew "bat"
brew "btop"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "starship"
brew "stow"
brew "zoxide"

# Development tools

brew "awscli"
brew "gh"
brew "git"
brew "gitmoni"
brew "gnupg"
brew "heroku"
brew "lazygit"

# Programming Languages

brew "golang"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "python@3.13"
brew "python@3.14"
brew "rust"

# Development libraries
brew "libpq", link: true
brew "libssl@3"
brew "libyaml"
